name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: pip3 install --user --verbose .
    - run: pip3 list
    - run: python3 --version
